export FLASK_APP=fleeter
export DATABASE_URL=postgresql://localhost:5432/fleeter

export AUTH0_DOMAIN=fleeter.auth0.com
export ALGORITHM=RS256
export API_AUDIENCE=fleeter

export TEST_DATABASE_URL=postgresql://localhost:5432/fleeter_test
export USER_CLIENT_ID=1cR4ZOIFhQ2218VYQ0L5Vdc9z7LRwpz2
export USER_CLIENT_SECRET=lHPfxJDcT6HynlLVUQ-SfYFhcTmPgY_9AxlCNQy88qm5KwGSMrc-X9DEqlYpJ_8M
export MOD_CLIENT_ID=LSLFxDjNTCsXrtcI7RAIzc8RNsv0L4Al
export MOD_CLIENT_SECRET=nLiIGEndblUCgIlj-dA7aj75i-9EM3YvsbDZs_hAmEa5C5fvVcKYa6S14URo1fPD