"""loosen length

Revision ID: 76479dc73795
Revises: ea069c88ccb6
Create Date: 2020-05-26 19:40:10.344898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76479dc73795'
down_revision = 'ea069c88ccb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fleets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('fleets', 'post',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=280),
               existing_nullable=False)
    op.alter_column('follow', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.alter_column('follow', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('fleets', 'post',
               existing_type=sa.String(length=280),
               type_=sa.VARCHAR(length=140),
               existing_nullable=False)
    op.alter_column('fleets', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
