"""auth0

Revision ID: dbc11ac269cc
Revises: 76479dc73795
Create Date: 2020-05-28 08:40:32.113051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbc11ac269cc'
down_revision = '76479dc73795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth0_id', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_users_auth0_id'), 'users', ['auth0_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_auth0_id'), table_name='users')
    op.drop_column('users', 'auth0_id')
    # ### end Alembic commands ###
